language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt59base qt59multimedia
    - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir install

after_success:
  - FILE=$(readlink -f install/linux/sACNView_*AppImage)
  - curl --upload-file .$FILE https://transfer.sh/$(basename $FILE)
