language: cpp
matrix:
  include:
      - os: linux
        dist: trusty
        sudo: required
        compiler: gcc
        before_install:
            # QT 5.9.2 Repo
            - sudo add-apt-repository ppa:beineri/opt-qt592-trusty -y
            - sudo apt-get update -qq
        install:
            # Install FPM
            - sudo apt-get -y install build-essential ruby ruby-dev
            - cd install/linux/ && cp _FPM_Makefile Makefile && make package && sudo dpkg -i fpm*.deb && fpm --version && cd ../../
            # QT
            - sudo apt-get -y install qt59base qt59multimedia
            - source /opt/qt*/bin/qt*-env.sh
        script:
            - qmake
            - make -j$(nproc)
        after_success:
          - FILE=$(readlink -f install/linux/sACNView_*AppImage)
          - curl --upload-file $FILE https://transfer.sh/$(basename $FILE)
          - FILE=$(readlink -f install/linux/sacnview_*.deb)
          - curl --upload-file $FILE https://transfer.sh/$(basename $FILE)

      - os: osx
        osx_image: xcode8.3
        before_install:
          - brew update
        install:
          # QT
          - brew install qt
          - brew link --force qt
        script:
          - qmake
          - make -j4
        after_success:
          - FILE=$(echo `pwd`/`ls install/mac/sACNView*.dmg`)
          - curl --upload-file $FILE https://transfer.sh/$(basename $FILE)
