#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
#branches:
#  # whitelist
#  only:
#    - master

# Start builds on tags only
#skip_non_tags: true

# Build worker image (VM template)
image: Visual Studio 2015

#---------------------------------#
#       build configuration       #
#---------------------------------#

environment:
  matrix:
    - QT_Ver: 5.9
    - QT_Ver: 5.6

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds

  # MSBuild verbosity level
  verbosity: detailed

init:
  - appveyor UpdateBuild -Version %APPVEYOR_REPO_COMMIT%

install:
  # MSVC Paths
  # https://www.appveyor.com/docs/lang/cpp/#visual-studio
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

  # QT Paths
  # https://www.appveyor.com/docs/build-environment/#qt
  - set QTDIR=C:\Qt\%QT_Ver%\msvc2015
  - set PATH=%PATH%;%QTDIR%\bin

  # NSIS Paths
  # https://www.appveyor.com/docs/build-environment/#tools
  - set PATH=%PATH%;C:\Program Files (x86)\NSIS

  # NSIS Plugin (SimpleFC)
  - appveyor DownloadFile http://nsis.sourceforge.net/mediawiki/images/d/d7/NSIS_Simple_Firewall_Plugin_1.20.zip
  - 7z e NSIS_Simple_Firewall_Plugin_1.20.zip -o"C:\Program Files (x86)\NSIS\Plugins\x86-ansi" SimpleFC.dll
  
  # Depot Tools
  - cd %APPVEYOR_BUILD_FOLDER%\..\..
  - appveyor DownloadFile https://storage.googleapis.com/chrome-infra/depot_tools.zip
  - 7z -bd x depot_tools.zip -odepot_tools
  - depot_tools\update_depot_tools
  - cd %APPVEYOR_BUILD_FOLDER%
  - PATH %APPVEYOR_BUILD_FOLDER%\..\..\depot_tools;%PATH%
  
  # Breakpad
  - cd %APPVEYOR_BUILD_FOLDER%\libs
  - mklink /j src breakpad
  - gclient config https://github.com/google/breakpad.git --unmanaged --name=src
  - gclient sync
  - del %APPVEYOR_BUILD_FOLDER%\libs\src /Q
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - qmake
  - nmake

artifacts:
  - path: install\win\*.exe
  - path: release\*.pdb
